### ISSUE TITLE
include and exclude errors from files doesn't filter data

### ISSUE THREAD

**Issue by AbhishekRamamurthy** [uber-go/nilaway#45] opened 2023-08-24 16:57 UTC
/src/go/bin/nilaway -include-errors-in-files /path_to_file/file_name.go ./...
 /src/go/bin/nilaway -exclude-errors-in-files /path_to_file/*test.go ./...
 
 doesn't mask errors from all other files, also use of wildcards yields the same result. 

If there is an example usage on how to use include and exclude files would be really helpful.

**Comment by sonalmahajan15** [comment] 2023-08-24 20:56
We don't have support for wildcards (regex) yet, but that's on the roadmap. Absolute paths should work, though. 

@yuxincs, could you provide examples demonstrating usage? Also, on a side note, could we add examples in the [wiki](https://github.com/uber-go/nilaway/wiki/Configuration) as well?

**Comment by yuxincs** [comment] 2023-09-08 14:31
As @sonalmahajan15 said, we currently do not support for regex or glob patterns when specifying include paths or exclude paths, only file prefixes are currently supported, for example:

`-include-errors-in-files="$(pwd)/mypkg" -exclude-errors-in-files="$(pwd)/mypkg/ignoredpkg"`

We will add regex support and add more examples in the wiki! 

In the meantime, you can use `-json` to print the errors in JSON format and do smarter post-processing there.

**Comment by sonic0002** [comment] 2023-11-24 14:07
want the same features here, especially we have lots of files auto-generated which wanna exclude

**Comment by deefdragon** [comment] 2023-11-29 05:56
It would also be nice to have wildcards to ignore tests.

**Comment by sonalmahajan15** [comment] 2023-11-30 07:32
Closing this as a duplicate of issue #99.

**Closed by sonalmahajan15** 2023-11-30 07:32 UTC
