### ISSUE TITLE
False positive at map[string]interface{} reassignment

### ISSUE THREAD

**Issue by liupangzi** [uber-go/nilaway#160] opened 2023-12-28 13:23 UTC
```
package main

func main() {
	m := make(map[string]interface{})
	m["a"] = m["b"]
}
```

nilaway would report: 
```
deep read from variable `m` lacking guarding; assigned deeply into local variable `m`
```

but `map[string]string` is OK.

**Comment by sonalmahajan15** [comment] 2023-12-28 19:31
@liupangzi: Thanks for reporting! This is actually a case of a known false positive, where NilAway was strictly prohibiting 
 a nilable deep assignment to a local variable. Here, in this case, an unguarded read of `m["b"]` was found to be the nilable source. We have PR #60 under review that implements a fix to address this false positive.

(Closing this issue as a duplicate of #59. Feel free to reopen the issue if you have further questions.)

**Closed by sonalmahajan15** 2023-12-28 19:31 UTC
