### ISSUE TITLE
Log.fatal is not considered terminal

### ISSUE THREAD

**Issue by nicois** [uber-go/nilaway#115] opened 2023-11-18 21:37 UTC
When a nil test ends with a call to `log.Fatal`, the analyser does not realise that execution will end, and appears to consider it as the same as other log methods.

**Comment by ksurent** [comment] 2023-11-20 20:46
Looks like a duplicate of #70.

**Comment by yuxincs** [comment] 2023-11-22 18:04
We indeed have a lot of terminal functions (as well as other abnormal control flows) to handle. Closing this as a duplicate of #70 . Let's continue the discussion there!

**Closed by yuxincs** 2023-11-22 18:04 UTC
