### ISSUE TITLE
false positive with debug.ReadBuildInfo()

### ISSUE THREAD

**Issue by bfallik** [uber-go/nilaway#117] opened 2023-11-19 16:29 UTC
Thanks for your great work on nilaway!

From a quick search I don't see this captured in another issue.

```
import (
	"runtime/debug"
)

func BuildInfo() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return "missing build info"
	}

        ...

	for _, kv := range info.Settings {
           ....
	}

        ....
}
```

From nilaway:

```
$  ~/go/bin/nilaway ./...
xxx/buildinfo.go:18:21: error: Potential nil panic detected. Observed nil flow from source to dereference point: 
	-> debug/mod.go:23:10: literal `nil` returned from `ReadBuildInfo()` in position 0
	-> xxx/buildinfo.go:18:21: result 0 of `ReadBuildInfo()` accessed field `Settings`
```

`info` is only nil of ok is false, in which case the function returns before accessing the `Settings` field.

Best,
brian

**Comment by dolmen** [comment] 2023-11-22 13:19
Here is a more general case of a pointer guarded by a `bool` that `nilaway` fails to recognize:

```go
package main

import (
	"fmt"
	"math/rand"
)

func buildX() (*int, bool) {
	if rand.Float32() > 0.5 {
		return nil, false
	}
	return new(int), true
}

func main() {
	x, ok := buildX()
	if !ok {
		return
	}
	fmt.Println(*x)
}
```

**Comment by dolmen** [comment] 2023-11-22 14:37
Duplicate of #77.

**Comment by yuxincs** [comment] 2023-11-22 17:57
Thanks for reporting this issue!

Closing this as a duplicate of #77, let's continue the discussion there.

(We do have a few PRs in the pipeline to handle user-defined `ok` forms, stay tuned!)

**Closed by yuxincs** 2023-11-22 17:57 UTC
