### ISSUE TITLE
NilAway reports false positive for a nil channel with context.WithCancel(context.Background())

### ISSUE THREAD

**Issue by tyree731** [uber-go/nilaway#124] opened 2023-11-20 17:45 UTC
Ran NilAway on some code of ours, and got a few messages to this effect:

```
broadcast_receiver.go:66:10: error: Potential nil panic detected. Observed nil flow from source to dereference point:
        -> context/context.go:184:9: literal `nil` returned from `Done()` in position 0
        -> context/context.go:105:2: returned as result 0 from interface method `Context.Done()` (implemented by `emptyCtx.Done()`)
        -> broadcast_receiver.go:66:10: result 0 of `Done()` uninitialized; nil channel accessed****
```

The code in question is selecting on `.Done()` for a `context`. That context is created as such:

```
ctx, cancel := context.WithCancel(context.Background())
```

Said selection happening in a separate function:

```
	for {
		select {
		case <-b.ctx.Done():
			return
		... more cases here...
		}
	}
```

While it is true that `context.Background()` creates an `emptyCtx`, that which can return a nil channel, when wrapping that `emptyCtx` with `context.WithCancel`, the resulting context is replaced with a `cancelCtx`, cancels being propagated (needlessly) to the emptyCtx, with cancelCtx not returning a nil channel.

This to me suggests this is a false positive.

**Comment by ioppermann** [comment] 2023-11-22 13:30
Same here. I get this false positive all over our codebase.

**Comment by dolmen** [comment] 2023-11-22 15:09
Duplicate of #98.

**Comment by yuxincs** [comment] 2023-11-22 16:40
Thanks for reporting such cases! We were aware of this issue (generally channels are not handled gracefully for now) and are brewing some PRs for a fix. 

Closing this issue as a duplicate of #98, let's continue the discussion there!

**Closed by yuxincs** 2023-11-22 16:40 UTC
