### ISSUE TITLE
nilaway doesn't acknowledge adding a guard check for a slice of a map value without a temporary

### ISSUE THREAD

**Issue by alecthomas** [uber-go/nilaway#118] opened 2023-11-20 00:57 UTC
First off: great project, thanks for open sourcing it.

Error message:

Code:

```go
	rules[state][rule].Mutator = Push(name)
```

Error:

```
chroma/mutators.go:147:2: index of a map of type `CompiledRules` lacking guarding; sliced into
```

Added guard check, but nilaway still complains.

```go
	if rule >= len(rules[state]) {
		return fmt.Errorf("invalid rule %d for state %q", rule, state)
	}
	rules[state][rule].Mutator = Push(name)
```

Assigning to a temporary placates it:

```go
	ruleState := rules[state]
	if rule >= len(ruleState) {
		return fmt.Errorf("invalid rule %d for state %q", rule, state)
	}
	ruleState[rule].Mutator = Push(name)
```

**Comment by dolmen** [comment] 2023-11-22 13:47
Please provide a self-contained example. Here it is not clear how type `CompiledRules` is defined.

**Comment by yuxincs** [comment] 2023-11-22 17:55
ACK! NilAway indeed does not handle deep slices and maps very well (cases like you mentioned `m[key1][key2][key3]`). This bits need more love and we have a few PRs that move toward that direction, e.g., #60 (won't exactly solve this, but we are working on this 😃 )

**Comment by yuxincs** [comment] 2023-11-22 18:15
BTW this is a duplicate of #111 , so I'm closing this one. Let's continue the discussion there!

**Closed by yuxincs** 2023-11-22 18:15 UTC
