### ISSUE TITLE
Nilaway reports impossible panic on http.Client

### ISSUE THREAD

**Issue by joeblubaugh** [uber-go/nilaway#119] opened 2023-11-20 03:25 UTC
```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	c := http.DefaultClient

	resp, err := c.Get("http://localhost:8080")
	if err != nil {
		panic(err)
	}

	fmt.Println(resp.StatusCode)
}
```

outputs:
```
❯ nilaway .
/Users/joe/workspace/nilawaytest/main.go:16:14: error: Potential nil panic detected. Observed nil flow from source to dereference point:
        -> http/client.go:644:12: unassigned variable `resp` returned from `do()` in position 0
        -> http/client.go:590:9: result 0 of `do()` returned from `Do()` in position 0
        -> http/client.go:488:9: result 0 of `Do()` returned from `Get()` in position 0
        -> nilawaytest/main.go:16:14: result 0 of `Get()` accessed field `StatusCode`
```

In client.go 's `Do()` function, there's a loop for processing redirects:
```go
	var resp *Response
	for {
		// For all but the first request, create the next
		// request hop and replace req.
		if len(reqs) > 0 {
			loc := resp.Header.Get("Location")
			if loc == "" {
				// While most 3xx responses include a Location, it is not
				// required and 3xx responses without a Location have been
				// observed in the wild. See issues #17773 and #49281.
/*Line 644 -->*/		return resp, nil
			}
			u, err := req.URL.Parse(loc)
			if err != nil {
				resp.closeBody()
				return nil, uerr(fmt.Errorf("failed to parse Location header %q: %v", loc, err))
			}
			host := ""
			if req.Host != "" && req.Host != req.URL.Host {
				// If the caller specified a custom Host header and the
				// redirect location is relative, preserve the Host header
				// through the redirect. See issue #22233.
				if u, _ := url.Parse(loc); u != nil && !u.IsAbs() {
					host = req.Host
				}
			}
			ireq := reqs[0]
			req = &Request{
				Method:   redirectMethod,
				Response: resp,
				URL:      u,
				Header:   make(Header),
				Host:     host,
				Cancel:   ireq.Cancel,
				ctx:      ireq.ctx,
			}
			if includeBody && ireq.GetBody != nil {
				req.Body, err = ireq.GetBody()
				if err != nil {
					resp.closeBody()
					return nil, uerr(err)
				}
				req.ContentLength = ireq.ContentLength
			}

			// Copy original headers before setting the Referer,
			// in case the user set Referer on their first request.
			// If they really want to override, they can do it in
			// their CheckRedirect func.
			copyHeaders(req)

			// Add the Referer header from the most recent
			// request URL to the new one, if it's not https->http:
			if ref := refererForURL(reqs[len(reqs)-1].URL, req.URL, req.Header.Get("Referer")); ref != "" {
				req.Header.Set("Referer", ref)
			}
			err = c.checkRedirect(req, reqs)

			// Sentinel error to let users select the
			// previous response, without closing its
			// body. See Issue 10069.
			if err == ErrUseLastResponse {
				return resp, nil
			}

			// Close the previous response's body. But
			// read at least some of the body so if it's
			// small the underlying TCP connection will be
			// re-used. No need to check for errors: if it
			// fails, the Transport won't reuse it anyway.
			const maxBodySlurpSize = 2 << 10
			if resp.ContentLength == -1 || resp.ContentLength <= maxBodySlurpSize {
				io.CopyN(io.Discard, resp.Body, maxBodySlurpSize)
			}
			resp.Body.Close()

			if err != nil {
				// Special case for Go 1 compatibility: return both the response
				// and an error if the CheckRedirect function failed.
				// See https://golang.org/issue/3795
				// The resp.Body has already been closed.
				ue := uerr(err)
				ue.(*url.Error).URL = loc
				return resp, ue
			}
		}

		reqs = append(reqs, req)
		var err error
		var didTimeout func() bool
		if resp, didTimeout, err = c.send(req, deadline); err != nil {
			// c.send() always closes req.Body
			reqBodyClosed = true
			if !deadline.IsZero() && didTimeout() {
				err = &httpError{
					err:     err.Error() + " (Client.Timeout exceeded while awaiting headers)",
					timeout: true,
				}
			}
			return nil, uerr(err)
		}

		var shouldRedirect bool
		redirectMethod, shouldRedirect, includeBody = redirectBehavior(req.Method, resp, reqs[0])
		if !shouldRedirect {
			return resp, nil
		}

		req.closeBody()
	}
```

It's impossible for `resp` to be nil on line 644, because the Header access on line 639 (`resp.Header.Get("Location")`) would result in a nil panic.

**Comment by rollulus** [comment] 2023-11-20 08:29
Funny, I was just digging through the same false positive. Which happened right after going through https://github.com/uber-go/nilaway/issues/97. And I was like: `http.Client` and `context.Context` are so ubiquitous, this surely can't be a false positive.

**Comment by dolmen** [comment] 2023-11-22 13:51
Duplicate of #126.

**Comment by yuxincs** [comment] 2023-11-22 16:15
Closed as a duplicate of https://github.com/uber-go/nilaway/issues/126. Let's continue the discussion there! Thanks for reporting such errors!

**Closed by yuxincs** 2023-11-22 16:15 UTC
